### PR TITLE
Simplify acp

### PR DESCRIPTION
**Pull request by kageiit**
- Remove unnecessary configuration and convention
- Move most configuration to extension
- Provide support to get android dependencies from any 'provided' like plugin
- When depending on project dependencies in apt configuration, also need to add a dependency on the `acp` configuration. This is not required once the compiler jar is packaged

### CODE REVIEW

**Comment by ZacSweers** [comment]
So to confirm, only the annotation processing library itself needs to specify the config but consumers of that processor later don't?

**Comment by kageiit** [comment]
> So to confirm, only the annotation processing library itself needs to specify the config but consumers of that processor later don't?

Correct. Consumers do not even know that acp was used. This approach is api-invisible

**Comment by ZacSweers** [comment]
Ignoring CI for now because I'll fix that later

**Comment by ZacSweers** [comment]
Thanks!

**Pull request merged**
